production:
  adapter: postgresql
  username: <%= ENV['PG_USER'] %>
  database: development
  host: localhost
  port: 5432 

development:
  adapter: postgresql
  username: <%= ENV['PG_USER'] %>
  database: development
  host: localhost
