production:
  adapter: postgresql
  username: user
  database: app-dev
  host: localhost

development:
  adapter: sqlite3
  database: development
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  host: localhost
