production:
  adapter: postgresql
  username: <%= ENV['PG_USER'] %>
  database: development
  host: localhost

development:
  adapter: postgresql
  username: <%= ENV['PG_USER'] %>
  database: development
  host: localhost
